platform:ios, '9.0'

target 'FunctionDemo' do
    pod 'UMCCommon'
    pod 'UMCAnalytics'
    pod 'UMCErrorCatch'
    pod 'AFNetworking'
    pod 'YYKit'
    pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'SDWebImage/WebP'
    pod 'SDWebImage/GIF' 
    pod 'MMKV'
    pod 'FMDB'
    pod 'CocoaAsyncSocket'
    pod 'TZImagePickerController'
end
